# A3: Agentic Sales Pipeline

## Initial Imports

In [1]:
# Warning control
import warnings
warnings.filterwarnings('ignore')

# Load environment variables
from utils import load_env
load_env()

import os
import yaml
from crewai import Agent, Task, Crew

## Load API tokens for our 3rd party APIs

In [2]:
os.environ['OPENAI_MODEL_NAME'] = 'gpt-4o-mini'

## Loading Tasks and Agents YAML files

In [3]:
# Define file paths for YAML configurations
files = {
    'lead_agents': 'config/A3_lead_qualification_agents.yaml',
    'lead_tasks': 'config/A3_lead_qualification_tasks.yaml',
    'email_agents': 'config/A3_email_engagement_agents.yaml',
    'email_tasks': 'config/A3_email_engagement_tasks.yaml'
}

# Load configurations from YAML files
configs = {}
for config_type, file_path in files.items():
    with open(file_path, 'r') as file:
        configs[config_type] = yaml.safe_load(file)

# Assign loaded configurations to specific variables
lead_agents_config = configs['lead_agents']
lead_tasks_config = configs['lead_tasks']
email_agents_config = configs['email_agents']
email_tasks_config = configs['email_tasks']

## Create Pydantic Models for Structured Output

In [4]:
from pydantic import BaseModel, Field
from typing import Dict, Optional, List, Set, Tuple

class LeadPersonalInfo(BaseModel):
    name: str = Field(..., description="The full name of the lead.")
    job_title: str = Field(..., description="The job title of the lead.")
    role_relevance: int = Field(..., ge=0, le=10, description="A score representing how relevant the lead's role is to the decision-making process (0-10).")
    professional_background: Optional[str] = Field(..., description="A brief description of the lead's professional background.")

class CompanyInfo(BaseModel):
    company_name: str = Field(..., description="The name of the company the lead works for.")
    industry: str = Field(..., description="The industry in which the company operates.")
    company_size: int = Field(..., description="The size of the company in terms of employee count.")
    revenue: Optional[float] = Field(None, description="The annual revenue of the company, if available.")
    market_presence: int = Field(..., ge=0, le=10, description="A score representing the company's market presence (0-10).")

class LeadScore(BaseModel):
    score: int = Field(..., ge=0, le=100, description="The final score assigned to the lead (0-100).")
    scoring_criteria: List[str] = Field(..., description="The criteria used to determine the lead's score.")
    validation_notes: Optional[str] = Field(None, description="Any notes regarding the validation of the lead score.")

class LeadScoringResult(BaseModel):
    personal_info: LeadPersonalInfo = Field(..., description="Personal information about the lead.")
    company_info: CompanyInfo = Field(..., description="Information about the lead's company.")
    lead_score: LeadScore = Field(..., description="The calculated score and related information for the lead.")

## Importing Tools

In [5]:
from crewai_tools import SerperDevTool, ScrapeWebsiteTool

## Lead Qualification Crew, Agents and Tasks

In [6]:
# Creating Agents
lead_data_agent = Agent(
  config=lead_agents_config['lead_data_agent'],
  tools=[SerperDevTool(), ScrapeWebsiteTool()]
)

cultural_fit_agent = Agent(
  config=lead_agents_config['cultural_fit_agent'],
  tools=[SerperDevTool(), ScrapeWebsiteTool()]
)

scoring_validation_agent = Agent(
  config=lead_agents_config['scoring_validation_agent'],
  tools=[SerperDevTool(), ScrapeWebsiteTool()]
)

# Creating Tasks
lead_data_task = Task(
  config=lead_tasks_config['lead_data_collection'],
  agent=lead_data_agent
)

cultural_fit_task = Task(
  config=lead_tasks_config['cultural_fit_analysis'],
  agent=cultural_fit_agent
)

scoring_validation_task = Task(
  config=lead_tasks_config['lead_scoring_and_validation'],
  agent=scoring_validation_agent,
  context=[lead_data_task, cultural_fit_task],
  output_pydantic=LeadScoringResult
)

# Creating Crew
lead_scoring_crew = Crew(
  agents=[
    lead_data_agent,
    cultural_fit_agent,
    scoring_validation_agent
  ],
  tasks=[
    lead_data_task,
    cultural_fit_task,
    scoring_validation_task
  ],
  verbose=True
)

## Email Engagement Crew

In [7]:
# Creating Agents
email_content_specialist = Agent(
  config=email_agents_config['email_content_specialist']
)

engagement_strategist = Agent(
  config=email_agents_config['engagement_strategist']
)

# Creating Tasks
email_drafting = Task(
  config=email_tasks_config['email_drafting'],
  agent=email_content_specialist
)

engagement_optimization = Task(
  config=email_tasks_config['engagement_optimization'],
  agent=engagement_strategist
)

# Creating Crew
email_writing_crew = Crew(
  agents=[
    email_content_specialist,
    engagement_strategist
  ],
  tasks=[
    email_drafting,
    engagement_optimization
  ],
  verbose=True
)

## Creating Complete Sales Flow

In [8]:
from crewai import Flow
from crewai.flow.flow import listen, start

class SalesPipeline(Flow):
    @start()
    def fetch_leads(self):
        # Pull our leads from the database
        leads = [
            {
                "lead_data": {
                    "name": "João Moura",
                    "job_title": "Director of Engineering",
                    "company": "Clearbit",
                    "email": "joao@clearbit.com",
                    "use_case": "Using AI Agent to do better data enrichment."
                },
            },
        ]
        return leads

    @listen(fetch_leads)
    def score_leads(self, leads):
        scores = lead_scoring_crew.kickoff_for_each(leads)
        self.state["score_crews_results"] = scores
        return scores

    @listen(score_leads)
    def store_leads_score(self, scores):
        # Here we would store the scores in the database
        return scores

    @listen(score_leads)
    def filter_leads(self, scores):
        return [score for score in scores if score['lead_score'].score > 70]

    @listen(filter_leads)
    def write_email(self, leads):
        scored_leads = [lead.to_dict() for lead in leads]
        emails = email_writing_crew.kickoff_for_each(scored_leads)
        return emails

    @listen(write_email)
    def send_email(self, emails):
        # Here we would send the emails to the leads
        return emails

flow = SalesPipeline()

## Plotting the Flow

In [9]:
flow.plot()

'/var/folders/pr/ct_8kb5d26l2mf90kt_6_jhh0000gn/T/crewai_flow_6y9vp0of/crewai_flow.html'

## Flow Kickoff

In [10]:
emails = await flow.kickoff_async()

Flow started with ID: 4e729740-2cb1-42e1-b33d-6ff0f216f360

Flow started with ID: 4e729740-2cb1-42e1-b33d-6ff0f216f360

╭──────────────────────────────────────────────── Flow Execution ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Starting Flow Execution                                                                                        │
│  Name: SalesPipeline                                                                                            │
│  ID: 4e729740-2cb1-42e1-b33d-6ff0f216f360                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────── Crew Execution Started ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Started                                                                                         │
│  Name: crew                                                                                                     │
│  ID: af42aa08-8a1d-4098-a6ad-eaa9bdaeefd4                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Data Specialist                                                                                    │
│                                                                                                                 │
│  Task: Collect and analyze the following information about the lead:                                            │
│  - Personal Information:                                                                                        │
│    - Name: Obtain the full name of the lead.                                                                    │
│    - Job Title: Determine the lead's current job title.                                                         │
│    - Role Relevance: Assess how relevant the lead's role is to the decision-making process on a scale from 0    │
│  to 10.                                                                                                         │
│    - Professional Background: Optionally, gather a brief description of the lead's professional background.     │
│                                                                                                                 │
│  - Company Information:                                                                                         │
│    - Company Name: Identify the name of the company the lead works for.                                         │
│    - Industry: Determine the industry in which the company operates.                                            │
│    - Company Size: Estimate the size of the company in terms of employee count.                                 │
│    - Revenue: If available, collect information on the annual revenue of the company.                           │
│    - Market Presence: Evaluate the company's market presence on a scale from 0 to 10.                           │
│                                                                                                                 │
│  - Our Company and Product:                                                                                     │
│    - Company Name: CrewAI                                                                                       │
│    - Product: Multi-Agent Orchestration Platform                                                                │
│    - ICP: Enterprise companies looking into Agentic automation.                                                 │
│    - Pitch: We are a platform that allows you to orchestrate AI Agents for automations to any vertical.         │
│                                                                                                                 │
│  -Lead Data:                                                                                                    │
│    {'name': 'João Moura', 'job_title': 'Director of Engineering', 'company': 'Clearbit', 'email':               │
│  'joao@clearbit.com', 'use_case': 'Using AI Agent to do better data enrichment.'}                               │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Data Specialist                                                                                    │
│                                                                                                                 │
│  Thought: I need to gather additional information about the lead João Moura and his company Clearbit. I         │
│  already have some of the personal information, but I'll need to find out more about his company, including     │
│  its industry, size, revenue, and market presence.                                                              │
│                                                                                                                 │
│  Using Tool: Search the internet with Serper                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────── Tool Input ───────────────────────────────────────────────────╮
│                                                                                                                 │
│  {                                                                                                              │
│    "search_query": "Clearbit company profile industry size revenue market presence"                             │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────── Tool Output ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  {'searchParameters': {'q': 'Clearbit company profile industry size revenue market presence', 'type':           │
│  'search', 'num': 10, 'engine': 'google'}, 'organic': [{'title': 'Leverage 100+ business data attributes',      │
│  'link': 'https://clearbit.com/attributes', 'snippet': 'Enrich your CRM and database, manage leads              │
│  efficiently, and enable marketing personalization with over 100 business data points.', 'position': 1},        │
│  {'title': 'Clearbit 2025 Company Profile: Valuation, Investors ...', 'link':                                   │
│  'https://pitchbook.com/profiles/company/101066-86', 'snippet': 'Information on acquisition, funding, cap       │
│  tables, investors, and executives for Clearbit. Use the PitchBook Platform to explore the full profile.',      │
│  'position': 2}, {'title': 'Clearbit - Overview, News & Similar companies', 'link':                             │
│  'https://www.zoominfo.com/c/clearbit/464190707', 'snippet': 'Clearbit, Inc. develops business intelligence to  │
│  help companies find more information of customers in order to increase sales and reduce fraud.', 'position':   │
│  3}, {'title': 'Fit: firmographic and employment data', 'link':                                                 │
│  'https://clearbit.com/resources/books/b2b-data/firmographic-demographic', 'snippet': 'Firmographic data:       │
│  company information, like size, type, industry, revenue, etc., indicating whether the company is a good fit    │
│  for your product or service.', 'position': 4}, {'title': 'Companies using Clearbit and its marketshare',       │
│  'link': 'https://enlyft.com/tech/products/clearbit', 'snippet': 'Clearbit is most often used by companies      │
│  with 10-50 employees and 1M-10M dollars in revenue. Our data for Clearbit usage goes back as far as 4 years    │
│  and 2 ...', 'position': 5}, {'title': '629 companies that use Clearbit', 'link':                               │
│  'https://bloomberry.com/data/clearbit/', 'snippet': 'We detected 629 customers using Clearbit, 3,018           │
│  companies that churned or ended their trial, and 11 customers with estimated renewals in the next 3 months.',  │
│  'position': 6}, {'title': 'How Clearbit hit $31.5M revenue and 907 customers in 2023.', 'link':                │
│  'https://getlat...                                                                                             │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Data Specialist                                                                                    │
│                                                                                                                 │
│  Thought: I found several sources that provide information about Clearbit, including its industry, size,        │
│  revenue, and market presence. I will review the relevant links for the necessary data.                         │
│                                                                                                                 │
│  Using Tool: Read website content                                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Data Specialist                                                                                    │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ### Personal Information                                                                                       │
│  - **Name:** João Moura                                                                                         │
│  - **Job Title:** Director of Engineering                                                                       │
│  - **Role Relevance:** 8                                                                                        │
│  - **Professional Background:** João Moura has a background in engineering and leadership, focusing on          │
│  integrating AI technologies for improved data management and enrichment processes.                             │
│                                                                                                                 │
│  ### Company Information                                                                                        │
│  - **Company Name:** Clearbit                                                                                   │
│  - **Industry:** Data Intelligence and Marketing Solutions                                                      │
│  - **Company Size:** Approximately 120 employees                                                                │
│  - **Revenue:** $31.5 million in 2023                                                                           │
│  - **Market Presence:** 8                                                                                       │
│                                                                                                                 │
│  ### Summary of Lead Information                                                                                │
│  - **Use Case:** Clearbit is currently using an AI agent for data enrichment purposes, aligning well with       │
│  CrewAI's offering as a Multi-Agent Orchestration Platform.                                                     │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: d8a03e24-1183-4f1d-ae27-7000b47f8d75                                                                     │
│  Agent: Lead Data Specialist                                                                                    │
│                                                                                                                 │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Task: Assess the cultural alignment between the lead's company and our organization by considering the         │
│  following:                                                                                                     │
│    - Cultural Values: Analyze the company's publicly stated values and internal culture (e.g., innovation,      │
│  sustainability, employee engagement).                                                                          │
│    - Strategic Alignment: Evaluate how well the company's goals and mission align with our organization's       │
│  strategic objectives.                                                                                          │
│    - Qualitative Scoring: Assign a qualitative score (0-10) representing the overall cultural fit.              │
│    - Comments: Provide additional comments or observations that support the cultural fit score.                 │
│                                                                                                                 │
│  - Our Company and Product:                                                                                     │
│    - Company Name: CrewAI                                                                                       │
│    - Product: Multi-Agent Orchestration Platform                                                                │
│    - ICP: Enterprise companies looking into Agentic automation.                                                 │
│    - Pitch: We are a platform that allows you to orchestrate AI Agents for automations to any vertical.         │
│                                                                                                                 │
│  - Lead Data:                                                                                                   │
│    {'name': 'João Moura', 'job_title': 'Director of Engineering', 'company': 'Clearbit', 'email':               │
│  'joao@clearbit.com', 'use_case': 'Using AI Agent to do better data enrichment.'}                               │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Thought: I need to gather specific information about Clearbit's cultural values, internal culture, and         │
│  overall mission before assessing the cultural fit with CrewAI.                                                 │
│                                                                                                                 │
│  Using Tool: Search the internet with Serper                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Thought: Thought: I found relevant information on Clearbit's company values and mission from their blog. I     │
│  will read the specific content to gather detailed insights about their culture and values.                     │
│                                                                                                                 │
│  Using Tool: Read website content                                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭────────────────────────────────────────────────── Tool Input ───────────────────────────────────────────────────╮
│                                                                                                                 │
│  {                                                                                                              │
│    "website_url": "https://clearbit.com/blog/company-values"                                                    │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Thought: Thought: I have gathered detailed information about Clearbit's company values and internal culture.   │
│  Now, I'll proceed to analyze the strategic alignment between Clearbit's goals and CrewAI's strategic           │
│  objectives.                                                                                                    │
│  CrewAI aims to provide a Multi-Agent Orchestration Platform, primarily targeting enterprise companies looking  │
│  into automations through AI agents. The use case presented by João Moura indicates Clearbit is using an AI     │
│  agent for data enrichment, which aligns well with CrewAI's offerings. Next, I will evaluate any additional     │
│  strategic insights from Clearbit that can help confirm this alignment.                                         │
│                                                                                                                 │
│  Using Tool: Search the internet with Serper                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭────────────────────────────────────────────────── Tool Input ───────────────────────────────────────────────────╮
│                                                                                                                 │
│  {                                                                                                              │
│    "search_query": "Clearbit mission statement and strategy"                                                    │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Thought: Thought: I still need to gather more information regarding Clearbit's mission and strategic           │
│  objectives to complete the cultural alignment assessment comprehensively. I'll read content from the relevant  │
│  links about Clearbit’s mission.                                                                                │
│                                                                                                                 │
│  Using Tool: Read website content                                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭────────────────────────────────────────────────── Tool Input ───────────────────────────────────────────────────╮
│                                                                                                                 │
│  {                                                                                                              │
│    "website_url": "https://clearbit.com/blog/the-new-clearbit-prospector"                                       │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  - Cultural fit score: 9/10                                                                                     │
│  - Supporting analysis:                                                                                         │
│    - Clearbit’s values of empathy, craft, and teamwork complement CrewAI’s innovative approach in AI            │
│  automation.                                                                                                    │
│    - Strategic objectives align as both companies leverage AI to improve business intelligence processes.       │
│    - The cultural emphasis on collaboration and customer focus strengthens the potential for a successful       │
│  partnership.                                                                                                   │
│    - Clearbit's proactive adaptability in corporate values indicates a suitable environment for long-term       │
│  cooperative success.                                                                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 04aa207d-bf7e-40bd-9946-8c22a4eba6a9                                                                     │
│  Agent: Cultural Fit Analyst                                                                                    │
│                                                                                                                 │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Scorer and Validator                                                                               │
│                                                                                                                 │
│  Task: Aggregate the collected data and perform the following steps: - Score Calculation: Based on predefined   │
│  criteria, calculate a final lead score (0-100). Consider factors such as:                                      │
│    - Role Relevance                                                                                             │
│    - Company Size                                                                                               │
│    - Market Presence                                                                                            │
│    - Cultural Fit                                                                                               │
│  - Scoring Criteria Documentation: List the criteria used to determine the score. - Validation: Review the      │
│  collected data and the calculated score for consistency and accuracy. Make adjustments if necessary. - Final   │
│  Report: Compile a summary report that includes the final validated lead score, the criteria used, and any      │
│  validation notes.                                                                                              │
│  - Our Company and Product:                                                                                     │
│    - Company Name: CrewAI                                                                                       │
│    - Product: Multi-Agent Orchestration Platform                                                                │
│    - ICP: Enterprise companies looking into Agentic automation.                                                 │
│    - Pitch: We are a platform that allows you to orchestrate AI Agents for automations to any vertical.         │
│                                                                                                                 │
│  - Lead Data:                                                                                                   │
│    {'name': 'João Moura', 'job_title': 'Director of Engineering', 'company': 'Clearbit', 'email':               │
│  'joao@clearbit.com', 'use_case': 'Using AI Agent to do better data enrichment.'}                               │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Scorer and Validator                                                                               │
│                                                                                                                 │
│  Thought: I need to gather data to validate the company information for Clearbit, checking its market presence  │
│  and size to ensure consistency in scoring the lead.                                                            │
│                                                                                                                 │
│  Using Tool: Search the internet with Serper                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────── Tool Input ───────────────────────────────────────────────────╮
│                                                                                                                 │
│  {                                                                                                              │
│    "search_query": "Clearbit company profile and market presence 2023"                                          │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────── Tool Output ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  {'searchParameters': {'q': 'Clearbit company profile and market presence 2023', 'type': 'search', 'num': 10,   │
│  'engine': 'google'}, 'organic': [{'title': 'The State of B2B Marketing Teams 2023', 'link':                    │
│  'https://clearbit.com/resources/reports/state-of-b2b-marketing-teams-2023', 'snippet': "From headcount to      │
│  seniority, martech stack, and more, here's a look at the average B2B tech marketing team in 2023.",            │
│  'position': 1}, {'title': 'Clearbit 2025 Company Profile: Valuation, Investors ...', 'link':                   │
│  'https://pitchbook.com/profiles/company/101066-86', 'snippet': 'Information on acquisition, funding, cap       │
│  tables, investors, and executives for Clearbit. Use the PitchBook Platform to explore the full profile.',      │
│  'position': 2}, {'title': 'The Data Download: May 2023', 'link':                                               │
│  'https://clearbit.com/blog/data-download-may-2023', 'snippet': "Welcome to the Data Download! Each month,      │
│  we'll be sharing highlights from our most recent Clearbit product releases.", 'position': 3}, {'title': 'How   │
│  Clearbit hit $31.5M revenue and 907 customers in 2023.', 'link': 'https://getlatka.com/companies/clearbit',    │
│  'snippet': "In 2023, Clearbit's revenue reached $31.5M up from $41.4M in 2022. The company previously          │
│  reported $41.4M in 2022, $41.4M in 2022, $3.4M in 2021, $3.4M in 2021.", 'position': 4}, {'title': 'Clearbit   │
│  - Overview, News & Similar companies', 'link': 'https://www.zoominfo.com/c/clearbit/464190707', 'snippet':     │
│  'Clearbit, Inc. develops business intelligence to help companies find more information of customers in order   │
│  to increase sales and reduce fraud.', 'position': 5}, {'title': 'Clearbit - 2025 Company Profile & Team',      │
│  'link': 'https://tracxn.com/d/companies/clearbit/__Ce8LwLChfXW6bZzY3dPGa0_FQQTE-gGHyGdZnzdvqT4', 'snippet':    │
│  "Explore Clearbit's in-depth company profile, including funding details, key investors, leadership, and        │
│  competitors.", 'position': 6}, {'title': "The Future of Clearbit's Free Tools", 'link':                        │
│  'https://clearbit.com/blog/the-future-of-clearbits-free-tools', '...                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Scorer and Validator                                                                               │
│                                                                                                                 │
│  Thought: Thought: I found relevant information about Clearbit's revenue and its current standing. The          │
│  information regarding its company size and market presence aligns with what I previously gathered, but I’ll    │
│  need to confirm the company size directly.                                                                     │
│                                                                                                                 │
│  Using Tool: Search the internet with Serper                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Lead Scorer and Validator                                                                               │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  Thought: I found confirmation that Clearbit has about 116 employees as of 2023. This is slightly different     │
│  than the initial estimate of 120 employees, but close enough to maintain consistency in scoring. Now, I can    │
│  perform the scoring calculations based on the gathered data.                                                   │
│                                                                                                                 │
│  ### Scoring Calculation                                                                                        │
│  1. **Role Relevance (10 points):** João Moura, as Director of Engineering, is highly relevant to               │
│  decision-making.                                                                                               │
│     - Score: **8**                                                                                              │
│                                                                                                                 │
│  2. **Company Size (10 points):** Clearbit has 116 employees, falling into the category of a medium-sized       │
│  enterprise.                                                                                                    │
│     - Score: **7** (Medium size covers companies with 100-250 employees)                                        │
│                                                                                                                 │
│  3. **Market Presence (10 points):** Clearbit has shown a robust market presence in data intelligence and       │
│  marketing solutions.                                                                                           │
│     - Score: **8**                                                                                              │
│                                                                                                                 │
│  4. **Cultural Fit (10 points):** The cultural fit is seen as strong due to shared values and objectives with   │
│  CrewAI.                                                                                                        │
│     - Score: **9**                                                                                              │
│                                                                                                                 │
│  ### Total Calculation                                                                                          │
│  - Total Score = (Role Relevance + Company Size + Market Presence + Cultural Fit) = 8 + 7 + 8 + 9 = **32 out    │
│  of 40**                                                                                                        │
│  - Final Lead Score (scaled to 100) = (32 / 40) * 100 = **80**                                                  │
│                                                                                                                 │
│  ### Validation Notes                                                                                           │
│  The calculated score appears to be consistent with the information gathered about João Moura and Clearbit.     │
│  The company size and market presence reflect recent information corroborated with external sources.            │
│                                                                                                                 │
│  Final Report:                                                                                                  │
│                                                                                                                 │
│  {                                                                                                              │
│    "personal_info": {                                                                                           │
│      "name": "João Moura",                                                                                      │
│      "job_title": "Director of Engineering",                                                                    │
│      "role_relevance": 8,                                                                                       │
│      "professional_background": "João Moura has a background in engineering and leadership, focusing on         │
│  integrating AI technologies for improved data management and enrichment processes."                            │
│    },                                                                                                           │
│    "company_info": {                                                                                            │
│      "company_name": "Clearbit",                                                                                │
│      "industry": "Data Intelligence and Marketing Solutions",                                                   │
│      "company_size": 116,                                                                                       │
│      "revenue": 31.5,                                                                                           │
│      "market_presence": 8                                                                                       │
│    },                                                                                                           │
│    "lead_score": {                                                                                              │
│      "score": 80,                                                                                               │
│      "scoring_criteria": [                                                                                      │
│        "Role Relevance",                                                                                        │
│        "Company Size",                                                                                          │
│        "Market Presence",                                                                                       │
│        "Cultural Fit"                                                                                           │
│      ],                                                                                                         │
│      "validation_notes": "The scoring metrics presented a consistent view with recent information regarding     │
│  Clearbit's company size and market presence."                                                                  │
│    }                                                                                                            │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: dfe20091-90b6-4127-8536-116c74a005f0                                                                     │
│  Agent: Lead Scorer and Validator                                                                               │
│                                                                                                                 │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Crew Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Completed                                                                                       │
│  Name: crew                                                                                                     │
│  ID: af42aa08-8a1d-4098-a6ad-eaa9bdaeefd4                                                                       │
│  Tool Args:                                                                                                     │
│  Final Output: Thought: I found confirmation that Clearbit has about 116 employees as of 2023. This is          │
│  slightly different than the initial estimate of 120 employees, but close enough to maintain consistency in     │
│  scoring. Now, I can perform the scoring calculations based on the gathered data.                               │
│                                                                                                                 │
│  ### Scoring Calculation                                                                                        │
│  1. **Role Relevance (10 points):** João Moura, as Director of Engineering, is highly relevant to               │
│  decision-making.                                                                                               │
│     - Score: **8**                                                                                              │
│                                                                                                                 │
│  2. **Company Size (10 points):** Clearbit has 116 employees, falling into the category of a medium-sized       │
│  enterprise.                                                                                                    │
│     - Score: **7** (Medium size covers companies with 100-250 employees)                                        │
│                                                                                                                 │
│  3. **Market Presence (10 points):** Clearbit has shown a robust market presence in data intelligence and       │
│  marketing solutions.                                                                                           │
│     - Score: **8**                                                                                              │
│                                                                                                                 │
│  4. **Cultural Fit (10 points):** The cultural fit is seen as strong due to shared values and objectives with   │
│  CrewAI.                                                                                                        │
│     - Score: **9**                                                                                              │
│                                                                                                                 │
│  ### Total Calculation                                                                                          │
│  - Total Score = (Role Relevance + Company Size + Market Presence + Cultural Fit) = 8 + 7 + 8 + 9 = **32 out    │
│  of 40**                                                                                                        │
│  - Final Lead Score (scaled to 100) = (32 / 40) * 100 = **80**                                                  │
│                                                                                                                 │
│  ### Validation Notes                                                                                           │
│  The calculated score appears to be consistent with the information gathered about João Moura and Clearbit.     │
│  The company size and market presence reflect recent information corroborated with external sources.            │
│                                                                                                                 │
│  Final Report:                                                                                                  │
│                                                                                                                 │
│  {                                                                                                              │
│    "personal_info": {                                                                                           │
│      "name": "João Moura",                                                                                      │
│      "job_title": "Director of Engineering",                                                                    │
│      "role_relevance": 8,                                                                                       │
│      "professional_background": "João Moura has a background in engineering and leadership, focusing on         │
│  integrating AI technologies for improved data management and enrichment processes."                            │
│    },                                                                                                           │
│    "company_info": {                                                                                            │
│      "company_name": "Clearbit",                                                                                │
│      "industry": "Data Intelligence and Marketing Solutions",                                                   │
│      "company_size": 116,                                                                                       │
│      "revenue": 31.5,                                                                                           │
│      "market_presence": 8                                                                                       │
│    },                                                                                                           │
│    "lead_score": {                                                                                              │
│      "score": 80,                                                                                               │
│      "scoring_criteria": [                                                                                      │
│        "Role Relevance",                                                                                        │
│        "Company Size",                                                                                          │
│        "Market Presence",                                                                                       │
│        "Cultural Fit"                                                                                           │
│      ],                                                                                                         │
│      "validation_notes": "The scoring metrics presented a consistent view with recent information regarding     │
│  Clearbit's company size and market presence."                                                                  │
│    }                                                                                                            │
│  }                                                                                                              │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Tracing Status ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Info: Tracing is disabled.                                                                                     │
│                                                                                                                 │
│  To enable tracing, do any one of these:                                                                        │
│  • Set tracing=True in your Crew/Flow code                                                                      │
│  • Set CREWAI_TRACING_ENABLED=true in your project's .env file                                                  │
│  • Run: crewai traces enable                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── Crew Execution Started ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Started                                                                                         │
│  Name: crew                                                                                                     │
│  ID: b9e39955-5487-4623-84a4-d92fc710a6c7                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Email Content Writer                                                                                    │
│                                                                                                                 │
│  Task: Craft a highly personalized email using the lead's name, job title, company information, and any         │
│  relevant personal or company achievements. The email should speak directly to the lead's interests and the     │
│  needs of their company. This is not as cold outreach as it is a follow up to a lead form, so keep it short     │
│  and to the point. Don't use any salutations or closing remarks, nor too complex sentences.                     │
│  Our Company and Product: - Company Name: CrewAI - Product: Multi-Agent Orchestration Platform - ICP:           │
│  Enterprise companies looking into Agentic automation. - Pitch: We are a platform that allows you to            │
│  orchestrate AI Agents for automations to any vertical.                                                         │
│  Use the following information: Personal Info: {'name': 'João Moura', 'job_title': 'Director of Engineering',   │
│  'role_relevance': 8, 'professional_background': 'João Moura has a background in engineering and leadership,    │
│  focusing on integrating AI technologies for improved data management and enrichment processes.'} Company       │
│  Info: {'company_name': 'Clearbit', 'industry': 'Data Intelligence and Marketing Solutions', 'company_size':    │
│  116, 'revenue': 31.5, 'market_presence': 8} Lead Score: {'score': 80, 'scoring_criteria': ['Role Relevance',   │
│  'Company Size', 'Market Presence', 'Cultural Fit'], 'validation_notes': "The scoring metrics presented a       │
│  consistent view with recent information regarding Clearbit's company size and market presence."}               │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

Output()

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Email Content Writer                                                                                    │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  João, as the Director of Engineering at Clearbit, your deep experience in integrating AI technologies to       │
│  enhance data management aligns perfectly with what CrewAI offers. Our Multi-Agent Orchestration Platform can   │
│  help streamline your automation processes, driving efficiency and innovation across your data intelligence     │
│  initiatives. Given Clearbit's impressive market presence and focus on marketing solutions, I believe our       │
│  platform can elevate your engineering initiatives while addressing any specific needs for automation in your   │
│  workflows. Let’s explore how we can work together to leverage AI agents effectively for Clearbit.              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 90f759f3-ab98-4b3f-9526-38e99d685d96                                                                     │
│  Agent: Email Content Writer                                                                                    │
│                                                                                                                 │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Engagement Optimization Specialist                                                                      │
│                                                                                                                 │
│  Task: Review the personalized email draft and optimize it with strong CTAs and engagement hooks. Keep in mind  │
│  they reached out and filled a lead form. Keep it short and to the point. Don't use any salutations or closing  │
│  remarks, nor too complex sentences. Ensure the email encourages the lead to schedule a meeting or take         │
│  another desired action immediately.                                                                            │
│  Our Company and Product: - Company Name: CrewAI - Product: Multi-Agent Orchestration Platform - ICP:           │
│  Enterprise companies looking into Agentic automation. - Pitch: We are a platform that allows you to            │
│  orchestrate AI Agents for automations to any vertical.                                                         │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Engagement Optimization Specialist                                                                      │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  João, CrewAI’s Multi-Agent Orchestration Platform can revolutionize Clearbit's automation processes. Imagine   │
│  streamlining your engineering initiatives while enhancing data intelligence. Take the first step toward        │
│  greater efficiency. **Schedule a 15-minute call** [here](#) to discuss how our platform can specifically meet  │
│  your automation needs. Don't miss out—let's unlock Clearbit's potential together. **Click this link** [to      │
│  book your slot now](#).                                                                                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 94800201-b709-461c-a0ce-5355624c5e38                                                                     │
│  Agent: Engagement Optimization Specialist                                                                      │
│                                                                                                                 │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Crew Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Completed                                                                                       │
│  Name: crew                                                                                                     │
│  ID: b9e39955-5487-4623-84a4-d92fc710a6c7                                                                       │
│  Tool Args:                                                                                                     │
│  Final Output: João, CrewAI’s Multi-Agent Orchestration Platform can revolutionize Clearbit's automation        │
│  processes. Imagine streamlining your engineering initiatives while enhancing data intelligence. Take the       │
│  first step toward greater efficiency. **Schedule a 15-minute call** [here](#) to discuss how our platform can  │
│  specifically meet your automation needs. Don't miss out—let's unlock Clearbit's potential together. **Click    │
│  this link** [to book your slot now](#).                                                                        │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Tracing Status ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Info: Tracing is disabled.                                                                                     │
│                                                                                                                 │
│  To enable tracing, do any one of these:                                                                        │
│  • Set tracing=True in your Crew/Flow code                                                                      │
│  • Set CREWAI_TRACING_ENABLED=true in your project's .env file                                                  │
│  • Run: crewai traces enable                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────────── Flow Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Flow Execution Completed                                                                                       │
│  Name: SalesPipeline                                                                                            │
│  ID: 4e729740-2cb1-42e1-b33d-6ff0f216f360                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

## Usage Metrics and Costs

Let’s see how much it would cost each time if this crew runs at scale.

In [11]:
import pandas as pd

# Convert UsageMetrics instance to a DataFrame
df_usage_metrics = pd.DataFrame([flow.state["score_crews_results"][0].token_usage.dict()])

# Calculate total costs
costs = 0.150 * df_usage_metrics['total_tokens'].sum() / 1_000_000
print(f"Total costs: ${costs:.4f}")

# Display the DataFrame
df_usage_metrics

Total costs: $0.0050

,total_tokens,prompt_tokens,cached_prompt_tokens,completion_tokens,successful_requests
0,33637,29670,0,3967,11

In [12]:
import pandas as pd

# Convert UsageMetrics instance to a DataFrame
df_usage_metrics = pd.DataFrame([emails[0].token_usage.dict()])

# Calculate total costs
costs = 0.150 * df_usage_metrics['total_tokens'].sum() / 1_000_000
print(f"Total costs: ${costs:.4f}")

# Display the DataFrame
df_usage_metrics

Total costs: $0.0002

,total_tokens,prompt_tokens,cached_prompt_tokens,completion_tokens,successful_requests
0,1180,963,0,217,2

## Inspecting Results

In [13]:
scores = flow.state["score_crews_results"]

In [14]:
import pandas as pd
from IPython.display import display, HTML

lead_scoring_result = scores[0].pydantic

# Create a dictionary with the nested structure flattened
data = {
    'Name': lead_scoring_result.personal_info.name,
    'Job Title': lead_scoring_result.personal_info.job_title,
    'Role Relevance': lead_scoring_result.personal_info.role_relevance,
    'Professional Background': lead_scoring_result.personal_info.professional_background,
    'Company Name': lead_scoring_result.company_info.company_name,
    'Industry': lead_scoring_result.company_info.industry,
    'Company Size': lead_scoring_result.company_info.company_size,
    'Revenue': lead_scoring_result.company_info.revenue,
    'Market Presence': lead_scoring_result.company_info.market_presence,
    'Lead Score': lead_scoring_result.lead_score.score,
    'Scoring Criteria': ', '.join(lead_scoring_result.lead_score.scoring_criteria),
    'Validation Notes': lead_scoring_result.lead_score.validation_notes
}

# Convert the dictionary to a DataFrame
df = pd.DataFrame.from_dict(data, orient='index', columns=['Value'])

# Reset the index to turn the original column names into a regular column
df = df.reset_index()

# Rename the index column to 'Attribute'
df = df.rename(columns={'index': 'Attribute'})

# Create HTML table with bold attributes and left-aligned values
html_table = df.style.set_properties(**{'text-align': 'left'}) \
                     .format({'Attribute': lambda x: f'<b>{x}</b>'}) \
                     .hide(axis='index') \
                     .to_html()

# Display the styled HTML table
display(HTML(html_table))

## Results

In [15]:
import textwrap

result_text = emails[0].raw
wrapped_text = textwrap.fill(result_text, width=80)
print(wrapped_text)

João, CrewAI’s Multi-Agent Orchestration Platform can revolutionize Clearbit's
automation processes. Imagine streamlining your engineering initiatives while
enhancing data intelligence. Take the first step toward greater efficiency.
**Schedule a 15-minute call** [here](#) to discuss how our platform can
specifically meet your automation needs. Don't miss out—let's unlock Clearbit's
potential together. **Click this link** [to book your slot now](#).

## How Complex Can it Get?

In [16]:
from crewai import Flow
from crewai.flow.flow import listen, start, and_, or_, router

class SalesPipeline(Flow):
    
  @start()
  def fetch_leads(self):
    # Pull our leads from the database
    # This is a mock, in a real-world scenario, this is where you would
    # fetch leads from a database
    leads = [
      {
        "lead_data": {
          "name": "João Moura",
          "job_title": "Director of Engineering",
          "company": "Clearbit",
          "email": "joao@clearbit.com",
          "use_case": "Using AI Agent to do better data enrichment."
        },
      },
    ]
    return leads

  @listen(fetch_leads)
  def score_leads(self, leads):
    scores = lead_scoring_crew.kickoff_for_each(leads)
    self.state["score_crews_results"] = scores
    return scores

  @listen(score_leads)
  def store_leads_score(self, scores):
    # Here we would store the scores in the database
    return scores

  @listen(score_leads)
  def filter_leads(self, scores):
    return [score for score in scores if score['lead_score'].score > 70]

  @listen(and_(filter_leads, store_leads_score))
  def log_leads(self, leads):
    print(f"Leads: {leads}")

  @router(filter_leads)
  def count_leads(self, scores):
    if len(scores) > 10:
      return 'high'
    elif len(scores) > 5:
      return 'medium'
    else:
      return 'low'

  @listen('high')
  def store_in_salesforce(self, leads):
    return leads

  @listen('medium')
  def send_to_sales_team(self, leads):
    return leads

  @listen('low')
  def write_email(self, leads):
    scored_leads = [lead.to_dict() for lead in leads]
    emails = email_writing_crew.kickoff_for_each(scored_leads)
    return emails

  @listen(write_email)
  def send_email(self, emails):
    # Here we would send the emails to the leads
    return emails

## Plotting the Flow

In [17]:
flow = SalesPipeline()
flow.plot()

'/var/folders/pr/ct_8kb5d26l2mf90kt_6_jhh0000gn/T/crewai_flow_jjd3d90q/crewai_flow.html'